export const Data = [
    {
        id: 1,
        title: "This is a title",
        category: "todo", 
        image: "",       
    },
    {
        id: 2,
        title: "This is a title",
        category: "todo", 
        image: "",       
    },
    {
        id: 3,
        title: "This is a title",
        category: "todo", 
        image: "",       
    },
    {
        id: 4,
        title: "This is a title",
        category: "todo", 
        image: "",       
    },
    {
        id: 5,
        title: "This is a title",
        category: "doing", 
        image: "",       
    },
    {
        id: 6,
        title: "This is a title",
        category: "doing", 
        image: "",       
    },
    {
        id: 7,
        title: "This is a title",
        category: "doing", 
        image: "",       
    },
    {
        id: 8,
        title: "This is a title",
        category: "doing", 
        image: "",       
    },
    {
        id: 9,
        title: "This is a title",
        category: "done", 
        image: "",       
    },
    {
        id: 10,
        title: "This is a title",
        category: "done", 
        image: "",       
    },
    {
        id: 11,
        title: "This is a title",
        category: "done", 
        image: "",       
    },
    {
        id: 12,
        title: "This is a title",
        category: "done", 
        image: "",       
    },
    {
        id: 13,
        title: "This is a title",
        category: "resources", 
        image: "",       
    },
    {
        id: 14,
        title: "This is a title",
        category: "resources", 
        image: "",       
    },
    {
        id: 15,
        title: "This is a title",
        category: "resources", 
        image: "",       
    },
    {
        id: 16,
        title: "This is a title",
        category: "resources", 
        image: "",       
    },
    {
        id: 17,
        title: "This is a title",
        category: "resources", 
        image: "",       
    },
]